Avatars
Adarsh-Patel-Dev/Quantum-CL pull request #2
Opened 2022-02-09 18:23 UTC by Adarsh-Patel-Dev

I have completed avatar component
Please review it

2022-02-09 18:37 UTC, Sahil25061999 commented on avatar/avatar.css
> +}
You can use rem here as well, remove comments if not necessary

2022-02-09 18:58 UTC, sri-rishi requested changes

2022-02-09 18:58 UTC, sri-rishi commented on avatar/avatar.css
> +    width: auto; ;
remove extra ; from here and use px for units less than 1rem

2022-02-09 19:06 UTC, swastika0015 commented
Apart from the changes mentioned above, everything looks good to me.

2022-02-10 03:07 UTC, rahulk31 commented on avatar/avatar.css
> +}
Recommendation: To specify similar width and height so that circle is perfectly shaped. As of now it is more like oval and will certainly change depending on the content.

2022-02-10 03:08 UTC, rahulk31 commented on avatar/avatar.html
> +
here and few more places, commented codes can be removed if not required.

2022-02-10 03:09 UTC, rahulk31 reviewed
Overall looks good to me. Great UI 💯 .

2022-02-10 12:29 UTC, Adarsh-Patel-Dev commented on avatar/avatar.html
> +
OK I'll remove that 
thanks for review

2022-02-10 13:18 UTC, Adarsh-Patel-Dev commented on avatar/avatar.css
> +}
Done

2022-02-10 13:19 UTC, merged