completed Toast
Adarsh-Patel-Dev/Quantum-CL pull request #8
Opened 2022-02-11 12:36 UTC by Adarsh-Patel-Dev

2022-02-11 12:49 UTC, kotesh-arya approved these changes
Follow that one suggestion and you are good to go for a merge 👍🏻

2022-02-11 12:49 UTC, kotesh-arya commented on toast/toast.html
> +            </p>
Just clear off these un-necessary gaps, rest is fine

2022-02-11 13:15 UTC, Adarsh-Patel-Dev commented on toast/toast.html
> +            </p>
Thanks I'll remove that extra space

2022-02-11 21:23 UTC, Vivek-jpg requested changes
other things looks good

2022-02-11 21:23 UTC, Vivek-jpg commented on toast/toast.css
> +    padding: 5px;
use rem in place of px

2022-02-12 07:22 UTC, Adarsh-Patel-Dev commented on toast/toast.css
> +    padding: 5px;
done

2022-02-12 07:22 UTC, merged